baseURL = 'https://b.liuhao.im/'
languageCode = 'zh-cn'
title = 'Hao'
summaryLength = 120
hasCJKLanguage = true
date_format = "2006.02.01"
enableRobotsTXT = true

[frontmatter]
date = [":filename", ":default"]

[services]
[services.disqus]
shortname = 'blog-ctpDc1LkF8'
